"""initial schema

Revision ID: 83302ff4ea29
Revises: 
Create Date: 2026-10-01 09:44:37.387368
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '83302ff4ea29'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_achievements_code')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=False)
    op.create_table('activity_categories',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('sports', 'games', 'outdoor', 'social', 'creative', 'fitness', 'other', name='activitycategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('venue_kind', sa.String(length=40), nullable=True),
    sa.Column('sport_slugs', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_activity_categories_slug')
    )
    op.create_index(op.f('ix_activity_categories_category'), 'activity_categories', ['category'], unique=False)
    op.create_index(op.f('ix_activity_categories_slug'), 'activity_categories', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'host', 'club_organizer', 'venue_manager', 'tournament_organizer', 'moderator', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False, comment='DEMO DATA marker - true for seeded demo accounts'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('clubs',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('sports', 'games', 'outdoor', 'social', 'creative', 'fitness', 'other', name='activitycategory'), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_clubs_slug')
    )
    op.create_index(op.f('ix_clubs_category'), 'clubs', ['category'], unique=False)
    op.create_index(op.f('ix_clubs_city'), 'clubs', ['city'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_owner_id'), 'clubs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 1', name='ck_leaderboard_entries_rank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'period', 'user_id', name='uq_leaderboard_entries_cat_period_user')
    )
    op.create_index(op.f('ix_leaderboard_entries_category'), 'leaderboard_entries', ['category'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_period'), 'leaderboard_entries', ['period'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('mmr_ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0', name='ck_mmr_ratings_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_mmr_ratings_user_category')
    )
    op.create_index(op.f('ix_mmr_ratings_category'), 'mmr_ratings', ['category'], unique=False)
    op.create_index(op.f('ix_mmr_ratings_user_id'), 'mmr_ratings', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('activity_invite', 'join_request', 'booking', 'payment', 'match_result', 'mmr_update', 'achievement', 'moderation', 'system', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('skill_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'any', name='skilllevel'), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'activity', 'message', 'review', 'club', 'venue', name='reporttargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'reviewing', 'resolved', 'dismissed', name='reportstatus'), nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_resolved_by_id'), 'reports', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_index(op.f('ix_reports_target_type'), 'reports', ['target_type'], unique=False)
    op.create_table('reviews',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('user', 'venue', 'activity', 'club', name='reviewtargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'target_type', 'target_id', name='uq_reviews_author_target')
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_type'), 'reviews', ['target_type'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_ach')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'any', name='skilllevel'), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_skills_user_name')
    )
    op.create_index(op.f('ix_user_skills_name'), 'user_skills', ['name'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('venues',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('category', sa.Enum('sports', 'games', 'outdoor', 'social', 'creative', 'fitness', 'other', name='activitycategory'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('venue_kind', sa.String(length=40), nullable=True),
    sa.Column('sport_slugs', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index(op.f('ix_venues_owner_id'), 'venues', ['owner_id'], unique=False)
    op.create_index(op.f('ix_venues_category'), 'venues', ['category'], unique=False)
    op.create_index(op.f('ix_venues_province'), 'venues', ['province'], unique=False)
    op.create_index(op.f('ix_venues_venue_kind'), 'venues', ['venue_kind'], unique=False)
    op.create_table('activities',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('category_link_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('sports', 'games', 'outdoor', 'social', 'creative', 'fitness', 'other', name='activitycategory'), nullable=False),
    sa.Column('skill_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', 'any', name='skilllevel'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'unlisted', 'private', name='activityvisibility'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('cost_per_person_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_participants > 0', name='ck_activities_max_participants'),
    sa.ForeignKeyConstraint(['category_link_id'], ['activity_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.create_index(op.f('ix_activities_category_link_id'), 'activities', ['category_link_id'], unique=False)
    op.create_index(op.f('ix_activities_club_id'), 'activities', ['club_id'], unique=False)
    op.create_index(op.f('ix_activities_host_id'), 'activities', ['host_id'], unique=False)
    op.create_index(op.f('ix_activities_starts_at'), 'activities', ['starts_at'], unique=False)
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=False)
    op.create_index(op.f('ix_activities_venue_id'), 'activities', ['venue_id'], unique=False)
    op.create_index(op.f('ix_activities_visibility'), 'activities', ['visibility'], unique=False)
    op.create_table('club_join_requests',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='clubjoinrequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_join_requests_club_user')
    )
    op.create_index(op.f('ix_club_join_requests_club_id'), 'club_join_requests', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_join_requests_reviewed_by_id'), 'club_join_requests', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_club_join_requests_status'), 'club_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_club_join_requests_user_id'), 'club_join_requests', ['user_id'], unique=False)
    op.create_table('club_members',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'host', 'club_organizer', 'venue_manager', 'tournament_organizer', 'moderator', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_members_club_user')
    )
    op.create_index(op.f('ix_club_members_club_id'), 'club_members', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_members_user_id'), 'club_members', ['user_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('warn', 'mute', 'suspend', 'ban', 'remove_content', 'restore_content', 'dismiss_report', name='moderationactiontype'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_actions_action'), 'moderation_actions', ['action'], unique=False)
    op.create_index(op.f('ix_moderation_actions_moderator_id'), 'moderation_actions', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_report_id'), 'moderation_actions', ['report_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_target_user_id'), 'moderation_actions', ['target_user_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('sports', 'games', 'outdoor', 'social', 'creative', 'fitness', 'other', name='activitycategory'), nullable=False),
    sa.Column('format', sa.Enum('single_elimination', 'double_elimination', 'round_robin', 'swiss', name='tournamentformat'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'in_progress', 'completed', 'cancelled', name='tournamentstatus'), nullable=False),
    sa.Column('max_entries', sa.Integer(), nullable=False),
    sa.Column('entry_fee_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_entries > 0', name='ck_tournaments_max_entries'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tournaments_slug')
    )
    op.create_index(op.f('ix_tournaments_category'), 'tournaments', ['category'], unique=False)
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_organizer_id'), 'tournaments', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_tournaments_slug'), 'tournaments', ['slug'], unique=False)
    op.create_index(op.f('ix_tournaments_starts_at'), 'tournaments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_index(op.f('ix_tournaments_venue_id'), 'tournaments', ['venue_id'], unique=False)
    op.create_table('venue_courts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surface', sa.String(length=60), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('hourly_price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('venue_kind', sa.String(length=40), nullable=True),
    sa.Column('resource_label', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_venue_courts_venue_name')
    )
    op.create_index(op.f('ix_venue_courts_venue_id'), 'venue_courts', ['venue_id'], unique=False)
    op.create_index(op.f('ix_venue_courts_venue_kind'), 'venue_courts', ['venue_kind'], unique=False)
    op.create_table('activity_participants',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'requested', 'confirmed', 'waitlisted', 'declined', 'cancelled', 'attended', 'no_show', name='participantstatus'), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_activity_participants_activity_user')
    )
    op.create_index(op.f('ix_activity_participants_activity_id'), 'activity_participants', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_participants_status'), 'activity_participants', ['status'], unique=False)
    op.create_index(op.f('ix_activity_participants_user_id'), 'activity_participants', ['user_id'], unique=False)
    op.create_table('activity_recurrences',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'biweekly', 'monthly', name='recurrencefrequency'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('by_weekday', sa.String(length=20), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_count >= 1', name='ck_activity_recurrences_interval'),
    sa.CheckConstraint('occurrence_count >= 1', name='ck_activity_recurrences_occurrences'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_recurrences_activity_id'), 'activity_recurrences', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_recurrences_frequency'), 'activity_recurrences', ['frequency'], unique=False)
    op.create_table('bookings',
    sa.Column('venue_court_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('booked_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', 'refunded', name='bookingstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_bookings_window'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booked_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_court_id'], ['venue_courts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_bookings_activity_id'), 'bookings', ['activity_id'], unique=False)
    op.create_index(op.f('ix_bookings_booked_by_id'), 'bookings', ['booked_by_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_venue_court_id'), 'bookings', ['venue_court_id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('type', sa.Enum('direct', 'group', 'activity', 'club', 'tournament', name='chatroomtype'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_activity_id'), 'chat_rooms', ['activity_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_club_id'), 'chat_rooms', ['club_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_created_by_id'), 'chat_rooms', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_tournament_id'), 'chat_rooms', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_type'), 'chat_rooms', ['type'], unique=False)
    op.create_table('check_ins',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_check_ins_activity_user')
    )
    op.create_index(op.f('ix_check_ins_activity_id'), 'check_ins', ['activity_id'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', 'disputed', name='matchstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_activity_id'), 'matches', ['activity_id'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_at'), 'matches', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('tournament_entries',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.Column('final_placement', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_entries_tournament_user')
    )
    op.create_index(op.f('ix_tournament_entries_tournament_id'), 'tournament_entries', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_tournament_entries_user_id'), 'tournament_entries', ['user_id'], unique=False)
    op.create_table('venue_availability',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('opens_at < closes_at', name='ck_venue_availability_window'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_venue_availability_weekday'),
    sa.ForeignKeyConstraint(['court_id'], ['venue_courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_availability_court_id'), 'venue_availability', ['court_id'], unique=False)
    op.create_index(op.f('ix_venue_availability_weekday'), 'venue_availability', ['weekday'], unique=False)
    op.create_table('chat_messages',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'file', 'system', name='messagetype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('match_participants',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'user_id', name='uq_match_participants_match_user')
    )
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_user_id'), 'match_participants', ['user_id'], unique=False)
    op.create_table('match_results',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'confirmed', 'disputed', 'verified', 'rejected', name='matchresultstatus'), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=False),
    sa.Column('team_b_score', sa.Integer(), nullable=False),
    sa.Column('winner_team', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mmr_applied', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_match_id'), 'match_results', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_results_status'), 'match_results', ['status'], unique=False)
    op.create_index(op.f('ix_match_results_submitted_by_id'), 'match_results', ['submitted_by_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'authorized', 'paid', 'failed', 'refunded', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('tournament_matches',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('home_entry_id', sa.UUID(), nullable=True),
    sa.Column('away_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('round_number >= 1', name='ck_tournament_matches_round'),
    sa.ForeignKeyConstraint(['away_entry_id'], ['tournament_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_entry_id'], ['tournament_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'slot', name='uq_tournament_matches_slot')
    )
    op.create_index(op.f('ix_tournament_matches_match_id'), 'tournament_matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_tournament_matches_round_number'), 'tournament_matches', ['round_number'], unique=False)
    op.create_index(op.f('ix_tournament_matches_tournament_id'), 'tournament_matches', ['tournament_id'], unique=False)
    op.create_table('mmr_history',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('match_result_id', sa.UUID(), nullable=True, comment='Idempotency key: one MMR delta per verified result'),
    sa.Column('rating_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_id'], ['mmr_ratings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_result_id', name='uq_mmr_history_match_result')
    )
    op.create_index(op.f('ix_mmr_history_match_result_id'), 'mmr_history', ['match_result_id'], unique=False)
    op.create_index(op.f('ix_mmr_history_rating_id'), 'mmr_history', ['rating_id'], unique=False)
    op.create_index(op.f('ix_mmr_history_user_id'), 'mmr_history', ['user_id'], unique=False)
    op.create_table('payment_splits',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('share_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'waived', 'refunded', name='splitstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('share_cents >= 0', name='ck_payment_splits_share'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'user_id', name='uq_payment_splits_payment_user')
    )
    op.create_index(op.f('ix_payment_splits_booking_id'), 'payment_splits', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payment_splits_payment_id'), 'payment_splits', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_splits_status'), 'payment_splits', ['status'], unique=False)
    op.create_index(op.f('ix_payment_splits_user_id'), 'payment_splits', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'processed', 'failed', name='refundstatus'), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_refunds_amount'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_provider_reference'), 'refunds', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_refunds_requested_by_id'), 'refunds', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('result_verifications',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'user_id', name='uq_result_verifications_result_user')
    )
    op.create_index(op.f('ix_result_verifications_result_id'), 'result_verifications', ['result_id'], unique=False)
    op.create_index(op.f('ix_result_verifications_user_id'), 'result_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_verifications_user_id'), table_name='result_verifications')
    op.drop_index(op.f('ix_result_verifications_result_id'), table_name='result_verifications')
    op.drop_table('result_verifications')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_requested_by_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_provider_reference'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payment_splits_user_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_status'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_payment_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_booking_id'), table_name='payment_splits')
    op.drop_table('payment_splits')
    op.drop_index(op.f('ix_mmr_history_user_id'), table_name='mmr_history')
    op.drop_index(op.f('ix_mmr_history_rating_id'), table_name='mmr_history')
    op.drop_index(op.f('ix_mmr_history_match_result_id'), table_name='mmr_history')
    op.drop_table('mmr_history')
    op.drop_index(op.f('ix_tournament_matches_tournament_id'), table_name='tournament_matches')
    op.drop_index(op.f('ix_tournament_matches_round_number'), table_name='tournament_matches')
    op.drop_index(op.f('ix_tournament_matches_match_id'), table_name='tournament_matches')
    op.drop_table('tournament_matches')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_match_results_submitted_by_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_status'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_match_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_match_participants_user_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_venue_availability_weekday'), table_name='venue_availability')
    op.drop_index(op.f('ix_venue_availability_court_id'), table_name='venue_availability')
    op.drop_table('venue_availability')
    op.drop_index(op.f('ix_tournament_entries_user_id'), table_name='tournament_entries')
    op.drop_index(op.f('ix_tournament_entries_tournament_id'), table_name='tournament_entries')
    op.drop_table('tournament_entries')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_activity_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_activity_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_chat_rooms_type'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_tournament_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_created_by_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_club_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_activity_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_bookings_venue_court_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booked_by_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_activity_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_activity_recurrences_frequency'), table_name='activity_recurrences')
    op.drop_index(op.f('ix_activity_recurrences_activity_id'), table_name='activity_recurrences')
    op.drop_table('activity_recurrences')
    op.drop_index(op.f('ix_activity_participants_user_id'), table_name='activity_participants')
    op.drop_index(op.f('ix_activity_participants_status'), table_name='activity_participants')
    op.drop_index(op.f('ix_activity_participants_activity_id'), table_name='activity_participants')
    op.drop_table('activity_participants')
    op.drop_index(op.f('ix_venue_courts_venue_id'), table_name='venue_courts')
    op.drop_table('venue_courts')
    op.drop_index(op.f('ix_tournaments_venue_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_starts_at'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_slug'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_organizer_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_category'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_moderation_actions_target_user_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_report_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_moderator_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_action'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_club_members_user_id'), table_name='club_members')
    op.drop_index(op.f('ix_club_members_club_id'), table_name='club_members')
    op.drop_table('club_members')
    op.drop_index(op.f('ix_club_join_requests_user_id'), table_name='club_join_requests')
    op.drop_index(op.f('ix_club_join_requests_status'), table_name='club_join_requests')
    op.drop_index(op.f('ix_club_join_requests_reviewed_by_id'), table_name='club_join_requests')
    op.drop_index(op.f('ix_club_join_requests_club_id'), table_name='club_join_requests')
    op.drop_table('club_join_requests')
    op.drop_index(op.f('ix_activities_visibility'), table_name='activities')
    op.drop_index(op.f('ix_activities_venue_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_index(op.f('ix_activities_starts_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_host_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_club_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_category_link_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_venues_owner_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_name'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_reviews_target_type'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_target_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_resolved_by_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mmr_ratings_user_id'), table_name='mmr_ratings')
    op.drop_index(op.f('ix_mmr_ratings_category'), table_name='mmr_ratings')
    op.drop_table('mmr_ratings')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_period'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_category'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_owner_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_city'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_category'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_activity_categories_slug'), table_name='activity_categories')
    op.drop_index(op.f('ix_activity_categories_category'), table_name='activity_categories')
    op.drop_table('activity_categories')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
